name: Build and Release APK

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Dependencies
      run: npm install
    
    - name: Sync Capacitor
      run: npx --yes @capacitor/cli cap sync android
    
    - name: Build APK
      uses: maierj/fastlane-action@v2.4.0
      with:
        lane: build_android
    
    - name: Upload APK to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: android/app/build/outputs/apk/release/app-release.apk
        asset_name: app-release.apk
        tag: ${{ github.ref }}
        overwrite: true
